## <span style="font-family: 'Computer Modern'; font-weight: bold; font-size: 32pt;">QCNNs for Classification (NEW)</span>
#### <span style="font-family: 'Computer Modern'; font-size: 18pt;">Introduction:</span> 
<span style="font-family: 'Computer Modern'; font-size: 14pt;">
In this notebook, we walk through the QCNN model and the logic used to generate our final results. This code is then streamlined (removing excess print statements and saving figures of interest) and condensed into the python file `qcnn_classify_phases.py` which was then run using cloud computing resources to accelerate the learning process. 

This notebook serves as a useful tool for anyone looking to play around with the model and generate some plots quickly. 

**NOTE:** This version of the notebook has been independently modified to be reliant on the PennyLane framework.
</span>

In [ ]:
# CODE NOT IN USE BELOW:

#----------------------------------------------------------------------------------------
# x_train = np.array([data[0] for data in train_images]) ## data for MNIST training data
# y_train = np.array(train_labels) ## labels/classifications for MNIST training data

# x_test = np.array([data[0] for data in test_images]) ## data for MNIST testing data
# y_test = np.array(test_labels) ## labels/classifications for MNIST testing data
#----------------------------------------------------------------------------------------

#### Shapes and types of each set:
#### Shape of train_images: torch.Size([24, 1, 28, 28])
#### Shape of train_labels: torch.Size([24])
#### Shape of test_images: torch.Size([14, 1, 28, 28])
#### Shape of test_labels: torch.Size([14])
#### Type of train_images: <class 'torch.Tensor'> ## same as test_images
#### Type of train_labels: <class 'torch.Tensor'> ## same as test_labels

***

In [77]:
# QML-Based Imports:
import pennylane as qml
from pennylane import numpy as np
import torch

# Data Recognition/Visualization Imports:
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rcParams.update(mpl.rcParamsDefault)
from tqdm import tqdm
import csv

# Data Analysis Imports:
import random # for generating random data
from sklearn import datasets # for data modeling/constructing
from sklearn.model_selection import train_test_split # for data modeling/constructing
from sklearn.svm import SVC # for data training

# PennyLane Demo-Based Imports (MNIST Data):
from pennylane.templates import RandomLayers

In [78]:
# TorchVision:
import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

In [79]:
# QML-Drawing-Based Imports:
import matplotlib.patches as patches

# QML Data-Based Imports:
from sklearn.preprocessing import OneHotEncoder # for encoding training and testing data labels

# NEW Imports:
import copy
import sys
from scipy.linalg import expm

***

<span style="font-family: 'Computer Modern'; font-weight: bold; font-size: 18pt;">FUNCTIONS / CLASSES</span>

In [80]:
# Gell Mann Matrix function:

def generate_gell_mann(order):
    """
    Generates a list of np.arrays which represent Gell Mann matrices of order 'order'.
    eg: order = 2
    gm_matrices = [ [[0,  1],
                             [1,  0]] ,

                            [[0, -i]
                             [i,  0]] ,

                            [[1,  0],
                             [0, -1]] ]
    """
    gm_matrices = []  # Initialize an empty list to store matrices:
    for k in range(order):
        j = 0
        while j < k:
            # Generate symmetric and anti-symmetric matrices:
            sym = b_mat(j, k, order) + b_mat(k, j, order)  # Create a symmetric matrix:
            # Create an anti-symmetric matrix:
            anti_sym = complex(0.0, -1.0) * (b_mat(j, k, order) - b_mat(k, j, order))
            gm_matrices.append(sym)  # Append symmetric matrix to list:
            gm_matrices.append(anti_sym)  # Append anti-symmetric matrix to list:
            j += 1

        if k < (order - 1):
            n = k + 1
            coeff = np.sqrt(2 / (n * (n + 1)))  # Calculate coefficient for diagonal matrix:

            sum_diag = b_mat(0, 0, order)  # Start with first diagonal element:
            for i in range(1, k + 1):
                sum_diag += b_mat(i, i, order)  # Sum up to k-th diagonal element:

            diag_mat = coeff * (sum_diag - n * (b_mat(k + 1, k + 1, order)))  # Create diagonal matrix:
            gm_matrices.append(diag_mat)  # Append diagonal matrix to list:

    # Return list of Gell-Mann matrices:
    return gm_matrices

In [81]:
# Convolutional Operator function:

def get_conv_op(mats, params):
    """
    Parametrizes the convolutional operator according to Gell-Mann matrices scaled by trainable parameters,
    this method generates the relevant applicable operator.
    """
    # Initialize a zero matrix with same shape as Gell-Mann matrices:
    final = np.zeros(mats[0].shape, dtype=np.complex128)
    for mat, param in zip(mats, params):  # Iterate over pairs of matrices and parameters:
        final += param * mat  # Accumulate weighted sum of matrices:

    # Return matrix exponential of final matrix:
    return expm(complex(0, -1) * final)

In [82]:
# Basis Matrix function:

def b_mat(i, j, n):
    """
    Generates an n x n matrix of 0s with the i,j th entry is a one.
    This is the i,j th basis vector on the space of n x n real matricies

    :param i: int, row index (must be < n)
    :param j: int, column index (must be < n)
    :param n: int, dimension of the matrices
    :return: np.array of floats, shape (n,n)
    """
    basis_matrix = np.zeros((n, n), dtype=np.float32)
    basis_matrix[i, j] = 1.0

    return basis_matrix

<span style="font-family: 'Computer Modern'; font-weight: bold; font-size: 18pt;">DATA</span>

<span style="font-family: 'Computer Modern'; font-size: 16pt;">_Loading / Processing_:</span>

In [163]:
# NOTE: This function uses TensorFlow to import the MNIST dataset, and due to environment errors, it is currently
# not in use. Intead, we import the MNIST dataset using TorchVision.

# Using TensorFLow (Currently Not in Use):
def load_mnist_tf():
    """
    Load the MNIST dataset and return training and testing images and labels, using TensorFlow.
    
    Returns:
        train_images (numpy.ndarray): Training images.
        train_labels (numpy.ndarray): Training labels.
        test_images (numpy.ndarray): Testing images.
        test_labels (numpy.ndarray): Testing labels.
    """
    # Load MNIST dataset using TensorFlow:
    (train_images, train_labels), (test_images, test_labels) = mnist.load_data()
    return train_images, train_labels, test_images, test_labels

In [164]:
# Define normalization transform:
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])

# Download and load train data:
# Note: Adjust directory based on your user directory.
trainset = datasets.MNIST(root='/Users/seanchisholm/NeutrinosSummer24/QML_Summer-2024/QML-JUNE/DATA', train=True,
                          transform=transform, download=True)
trainloader = DataLoader(trainset, batch_size=1000, shuffle=True)

# Download and load test data:
# Note: Adjust directory based on User
testset = datasets.MNIST(root='/Users/seanchisholm/NeutrinosSummer24/QML_Summer-2024/QML-JUNE/DATA', train=False,
                         transform=transform, download=True)
testloader = DataLoader(testset, batch_size=1000, shuffle=False)

# Extract data from loaders:
train_images, train_labels = next(iter(trainloader))
test_images, test_labels = next(iter(testloader))

# Print relevant shapes and types:
print("Shape of train_images:", train_images.shape)
print("Shape of train_labels:", train_labels.shape)
print("Shape of test_images:", test_images.shape)
print("Type of train_images:", type(train_images))
print("Type of train_labels:", type(train_labels))

Shape of train_images: torch.Size([1000, 1, 28, 28])
Shape of train_labels: torch.Size([1000])
Shape of test_images: torch.Size([1000, 1, 28, 28])
Type of train_images: <class 'torch.Tensor'>
Type of train_labels: <class 'torch.Tensor'>


<span style="font-family: 'Computer Modern'; font-size: 16pt;">_Reduction_:</span>

In [165]:
# Multi-Classification -> Binary Classification:
#------------------------------------------------------------------------
# Select indices for classes 0 and 1 in train_labels:
train_idx = np.append(np.where(train_labels.numpy() == 0)[0][:n_train//2],
                      np.where(train_labels.numpy() == 1)[0][:n_train//2])

# Select indices for classes 0 and 1 in test_labels:
test_idx = np.append(np.where(test_labels.numpy() == 0)[0][:n_test//2],
                     np.where(test_labels.numpy() == 1)[0][:n_test//2])

# Convert indices to PyTorch tensors:
train_idx = torch.tensor(train_idx, dtype=torch.long)
test_idx = torch.tensor(test_idx, dtype=torch.long)

# Filter training and testing data based on 'train_idx' and 'test_idx':
train_images = train_images[train_idx]
test_images = test_images[test_idx]

# Filter labels based on based on 'train_idx' and 'test_idx':
train_labels = train_labels[train_idx]
test_labels = test_labels[test_idx]
#------------------------------------------------------------------------

# Reduce dataset size:
n_train = 100
n_test = 50
train_images = train_images[:n_train]
train_labels = train_labels[:n_train]
test_images = test_images[:n_test]
test_labels = test_labels[:n_test]

# Normalize pixel values within [0,1]:
train_images = train_images / 255.0
test_images = test_images / 255.0

# Print relevant shapes and types V2:
print("Shape of train_images:", train_images.shape)
print("Shape of train_labels:", train_labels.shape)
print("Shape of test_images:", test_images.shape)
print("Shape of test_labels:", test_labels.shape)
print("Type of train_images:", type(train_images))
print("Type of train_labels:", type(train_labels))

Shape of train_images: torch.Size([100, 1, 28, 28])
Shape of train_labels: torch.Size([100])
Shape of test_images: torch.Size([50, 1, 28, 28])
Shape of test_labels: torch.Size([50])
Type of train_images: <class 'torch.Tensor'>
Type of train_labels: <class 'torch.Tensor'>


<span style="font-family: 'Computer Modern'; font-size: 16pt;">_Flattening_:</span>

In [166]:
# Flatten images:
train_images = train_images.reshape(train_images.shape[0], -1)
test_images = test_images.reshape(test_images.shape[0], -1)
# Reshape arrays to add 240 zeroes to each dataset:
test_images = np.pad(test_images, ((0, 0), (0, 240)), mode='constant', constant_values=0.0)
train_images = np.pad(train_images, ((0, 0), (0, 240)), mode='constant', constant_values=0.0)

# Print relevant shapes and types V3:
print("Shape of train_images:", train_images.shape)
print("Shape of train_labels:", train_labels.shape)
print("Shape of test_images:", test_images.shape)
print("Type of train_images:", type(train_images))
print("Type of train_labels:", type(train_labels))

Shape of train_images: (100, 1024)
Shape of train_labels: torch.Size([100])
Shape of test_images: (50, 1024)
Type of train_images: <class 'pennylane.numpy.tensor.tensor'>
Type of train_labels: <class 'torch.Tensor'>


***

<span style="font-family: 'Computer Modern'; font-weight: bold; font-size: 18pt;">QCNN MODEL</span>

<span style="font-family: 'Computer Modern'; font-size: 14pt;">_Layers_:</span>

In [167]:
# Analyzing Weights Shape/Size/Behavior:

n_qubits = 2 # Define number of qubits
ex_params = np.random.uniform(0, np.pi, size=(2, n_qubits, 3))
print(ex_params)

# Parameter Shape:
print(ex_params.shape)

# Parameter Length:
print(len(ex_params))

[[[2.75318587 0.15459607 1.40999534]
  [2.68850444 0.84130027 1.3562959 ]]

 [[1.82995065 3.01767526 0.87808793]
  [2.03410484 1.35482253 0.93940217]]]
(2, 2, 3)
2


In [168]:
# Convolutional Layer Function:
def quantum_conv_layer(weights):
    """
    Applies a quantum convolutional layer.
    """
    n_qubits = 2  # Number of qubits is second dimension of weights
    
    for i in range(0, n_qubits, 2):
        # First rotation on second qubit of pair:
        qml.RZ(-np.pi/2, wires=i + 1)
        
        # First set of rotations on first qubit of pair:
        qml.RZ(weights[0][i][0], wires=i)
        qml.RY(weights[0][i][1], wires=i + 1)
        
        # First CNOT gate:
        qml.CNOT(wires=[i, i + 1])
        
        # Second set of rotations on second qubit of pair:
        qml.RY(weights[0][i][2], wires=i + 1)
        
        # Second CNOT gate:
        qml.CNOT(wires=[i + 1, i])
        
        # Second rotation on first qubit of pair:
        qml.RZ(np.pi/2, wires=i)

In [169]:
# Pooling Layer Function:
def pennylane_pool_layer():
    """
    Applies two-qubit pooling operation to inputted qubits, including controlled rotation based on 
    measurement.
    """
    n_qubits = 2  # Determine number of qubits from weights shape:

    # Generate Gell-Mann matrices for 2-D space (single qubit operators):
    pool_operators = generate_gell_mann(2)  # NEW FUNC
    
    # Loop over active qubits in pairs # FOR PAIRS OF QUBITS
    for i in range(0, n_qubits, 2):  # FOR PAIRS OF QUBITS
        q1 = i        # First qubit:
        q2 = i + 1    # Second qubit:

        # Extract weights for current qubit pair:
        new_weights = weights[:, i, :]  # Shape (a, 3):

        # Get convolutional operators V1 and V2 from pool operators and weights:
        v1 = get_conv_op(pool_operators, new_weights[0])  # Use first set of weights for V1  # NEW FUNC
        v2 = get_conv_op(pool_operators, new_weights[1])  # Use second set of weights for V2  # NEW FUNC

        # Apply Hadamard gate to first qubit:
        qml.Hadamard(wires=q1)
        
        # Apply first controlled unitary operation:
        qml.ControlledQubitUnitary(v1, control_wires=[q1], wires=[q2])
        
        # Apply Hadamard gate to second qubit:
        qml.Hadamard(wires=q2)
        
        # Apply second controlled unitary operation:
        qml.ControlledQubitUnitary(v2, control_wires=[q2], wires=[q1])

<span style="font-family: 'Computer Modern'; font-weight: bold; font-size: 15pt;">_Circuit_:</span>

In [170]:
# Define device(s):
n_qubits = 2  # Number of qubits
dev = qml.device("default.qubit", wires=n_qubits)

# QCNN:
@qml.qnode(dev, interface='autograd')
def q_conv_circuit(params, x):
    """
    Defines a quantum circuit for training. This circuit encodes the input features using RX gates, applies
    two quantum convolutional layers interleaved with a pooling layer, and measures the expectation value of
    Pauli-Z on the first qubit.
    """
    # Apply Amtplitude Embedding:
    qml.AmplitudeEmbedding(x, wires=range(n_qubits), normalize=True)
    
    # Apply first convolutional layer function, pass 'params' as argument:
    quantum_conv_layer(params)

    # Apply pooling layer, pass 'params' as argument:
    pennylane_pool_layer(params)
    
    # Return measure of the PauliZ expectation value:
    return [qml.expval(qml.PauliZ(wire)) for wire in range(0, n_qubits, 2)]

***

<span style="font-family: 'Computer Modern'; font-weight: bold; font-size: 18pt;">TRAINING</span>

<span style="font-family: 'Computer Modern'; font-size: 16pt;">_Weights_:</span>

In [182]:
def preprocess_params(params, n_qubits=2):
    # Flatten images:
    params_flat = params.reshape(-1)
    
    # Desired length for amplitude embedding:
    opt_length = 2**n_qubits
    
    # Pad or truncate to match opt_length:
    if len(params_flat) < opt_length:
        # Pad with zeros to size of opt_length:
        params_flat = np.pad(params_flat, (0, opt_length - len(params_flat)), mode='constant', constant_values=0.0)
    else:
        # Truncate to opt_length:
        params_flat = params_flat[:opt_length]
    
    return params_flat

# Initialize weights:
weight_shapes = {"params": (2, n_qubits, 3)}
qcnn_weights =  np.random.uniform(0, np.pi, size=(2, n_qubits, 3))
qcnn_weights_flat = preprocess_params(qcnn_weights, n_qubits=2)

# Print relevant shapes and types V5:
print(f"Shape of Example Parameter: {qcnn_weights[0].shape}")
print("Shape of 'params':", qcnn_weights.shape)
print("Type of 'params':", type(qcnn_weights))
print("Shape of 'params0':", qcnn_weights_flat.shape)
print("Type of 'params0':", type(qcnn_weights_flat))

Shape of Example Parameter: (2, 3)
Shape of 'params': (2, 2, 3)
Type of 'params': <class 'pennylane.numpy.tensor.tensor'>
Shape of 'params0': (4,)
Type of 'params0': <class 'pennylane.numpy.tensor.tensor'>


<span style="font-family: 'Computer Modern'; font-size: 16pt;">_Cost_:</span>

In [180]:
# Mean Squared Error (MSE) function:
def mse_cost(params, x, y):
    """
    Computes the Mean Squared Error (MSE) cost function.
    """
    predictions = np.array([q_conv_circuit(params, xi) for xi in x])
    return np.mean((predictions - y) ** 2)

<span style="font-family: 'Computer Modern'; font-size: 16pt;">_Optimization_:</span>

In [183]:
# ORIGINAL: Currently Not Operative

# Training and Testing Data Instantiation:
#------------------------------------------------------------------------
x_train = np.array([data[0] for data in train_images])
x_test = np.array([data[0] for data in test_images])

y_train = np.array(train_labels)
y_test = np.array(test_labels)
#------------------------------------------------------------------------

# Define relevant cost function (Using MSE for now):
cost = mse_cost # sets cost func to mean squared error

# Training loop:
opt = qml.GradientDescentOptimizer(stepsize=0.4)
num_steps = 100

# Optimization step:
for step in range(num_steps):
    params = opt.step(lambda v: cost(v, x_train, y_train), qcnn_weights)
    if step % 10 == 0:
        loss = cost(params, x_train, y_train)
        print(f"Step {step}: cost = {loss}")

# Evaluate optimization on sample test data:
x_test = np.array([data[0] for data in test_states])
predictions = np.array([q_conv_circuit(qcnn_weights, xi) for xi in x_test])

ValueError: Features must be a one-dimensional tensor, or two-dimensional with batching; got shape (2, 2, 3).

In [ ]:
# NEW: Stochastic Gradient Descent (In Progress)

# Parameters for optimization:
learning_rate = 0.01
num_steps = 100
batch_size = 32

# Initialize parameters:
n_qubits = 2  # Number of qubits
dev = qml.device("default.qubit", wires=n_qubits)
params = np.random.uniform(0, np.pi, size=(2, n_qubits, 3))
# params = params.flatten()

def stoch_grad_descent(params, x, y, learning_rate, batch_size):
    # Shuffle data:
    permutation = np.random.permutation(len(x))
    x = x[permutation]
    y = y[permutation]

    # Process each batch:
    for i in range(0, len(x), batch_size):
        x_batch = x[i:i + batch_size]
        y_batch = y[i:i + batch_size]

        # Compute gradient:
        grad_cost = qml.grad(mse_cost, argnum=0)
        gradients = grad_cost(params, x_batch, y_batch)

        # Update parameters:
        params = params - learning_rate * gradients

    return params

step_size = 5

# Training loop:
for step in range(num_steps):
    qcnn_weights = stoch_grad_descent(qcnn_weights, training_data, training_labels, learning_rate, batch_size)
    if step % step_size == 0:
        loss = mse_cost(qcnn_weights, training_data, training_labels)
        print(f"Step {step}: cost = {loss}")

# Evaluate optimization on sample test data:
x_test = np.array([data for data in testing_data])
predictions = np.array([q_conv_circuit(params, xi) for xi in x_test])

<span style="font-family: 'Computer Modern'; font-size: 16pt;">_Accuracy_:</span>

In [71]:
# Convert continuous predictions to class labels (-1 or 1), depending on value distance:
predicted_labels = np.where(predictions >= 0, 1, -1)

# Calculate accuracy:
def calculate_accuracy(y_true, y_pred):
    correct_predictions = np.sum(y_true == y_pred)
    total_predictions = len(y_true)
    accuracy = correct_predictions / total_predictions
    return accuracy

# Compute accuracy on test dataset:
accuracy = calculate_accuracy(y_test, predictions)
print(f'Accuracy: {accuracy * 100:.2f}%')

NameError: name 'predictions' is not defined

***

<span style="font-family: 'Computer Modern'; font-weight: bold; font-size: 18pt;">APPENDIX: _More Circuits, Gates, and Drawings_</span>

<span style="font-family: 'Computer Modern'; font-size: 14pt;">_Test Parameter Re-Initialization_:</span>

In [4]:
# Analyzing Weights Shape/Size/Behavior:
n_qubits = 2 # Define number of qubits

# Instantiate parameters:
ex_params = np.random.uniform(0, np.pi, size=(2, n_qubits, 3))
print(ex_params)

# Parameter Shape:
print(ex_params.shape)

# Parameter Length:
print(len(ex_params))

# Parameter Size Extraction:
w_length = ex_params.shape[-1]
print(w_length)

[[[0.70843918 2.47357609 1.35955782]
  [2.25947246 1.93188041 2.59359611]]

 [[0.68078307 0.54831338 0.52074872]
  [0.65102898 2.2527576  2.72282781]]]
(2, 2, 3)
2
3


<span style="font-family: 'Computer Modern'; font-size: 14pt;">_Gates_:</span>

In [5]:
# Custom General Rotation Gate for (variable) size/shape of weights and wires:
def G_Rot(weights, wire):
    """General Rotation Gate to Qubit."""
    qml.Rot(weights[0], weights[1], weights[2], wires=wire)

<span style="font-family: 'Computer Modern'; font-size: 14pt;">_Circuits_:</span>

In [10]:
# With general roations, no 'G_Rot':

def two_qubit_pooling(weights):
    
    # Important parameter values:
    n_qubits = 2
    n_weights = weights.shape[-1]
    
    # Apply Rotations/Gates before Measurement:
    for i in range(0, n_qubits, 2):
        # First set of Rotations (Qubit 1):
        qml.Rot(weights[0][i][0], weights[0][i][1], weights[0][i][2], wires=i)
        
        # First set of Rotations (Qubit 2):
        qml.Rot(weights[0][i+1][0], weights[0][i+1][1], weights[0][i+1][2], wires=i+1)
    
        # First set of CNOT Gates (Qubit 1):
        qml.CNOT(wires=[i, i+1])
    
        # Second set of Rotations (Qubit 1):
        qml.Rot(weights[1][i][0], weights[1][i][1], weights[1][i][2], wires=i)
    
        # Second set of Rotations (Qubit 2):
        qml.Rot(weights[1][i+1][0], weights[1][i+1][1], weights[1][i+1][2], wires=i+1)
    
        # Second set of CNOT Gates (Qubit 2):
        qml.CNOT(wires=[i, i+1])
    
        # Apply controlled rotations (CRot) directly:
        qml.CRot(weights[2][i][0], weights[2][i][1], weights[2][i][2], wires=[i, i+1])
    
    # NOTE: I commented out the PauliZ measure from the pooling function here, but this was strictly to be able to
    # use qml.draw below to visualize my results, which requires me to instantiate a circuit uses the layer 
    # function and returns a measure. When applied to the QCNN as a whole, this needs to be commented back in, or
    # else no dimensionality reduction will occur in the QCNN.
    
    # Perform PauliZ measure to every other Qubit:
    #for wire in range(0, n_qubits, 2):
    #    qml.expval(qml.PauliZ(wire))

<span style="font-family: 'Computer Modern'; font-size: 14pt;">_Drawings_:</span>

<span style="font-family: 'Computer Modern'; font-weight: bold; font-size: 12pt;">Drawing #1: _Original Pooling Layer w/ "Every Other Qubit" Measure (Not Used Currently)_</span>

In [11]:
# Example Usage #1:

n_qubits = 2
dev = qml.device('default.qubit', wires=n_qubits)

# Circuit 1: Every Other Qubit
#------------------------------------------------------------------------------
@qml.qnode(dev)
def circuit1(weights):
    two_qubit_pooling(weights)
    return [qml.expval(qml.PauliZ(wire)) for wire in range(0, n_qubits, 2)]
#------------------------------------------------------------------------------

weights = np.random.random((3, n_qubits, 3))  # Example weights
print(f'Pooling Layer Results (2 Qubits) #1:')
print(circuit1(weights))

# Draw Circuit Layer:
unit_drawer1 = qml.draw(circuit1)
print(f' -> Pooling Layer with PauliZ Measure @ "Every Other Qubit":')
print(f'-------------------------------------------------------------------------------')
print(unit_drawer1(weights))
print(f'-------------------------------------------------------------------------------\n\n')

Pooling Layer Results (2 Qubits) #1:
[tensor(0.77182558, requires_grad=True)]
 -> Pooling Layer with PauliZ Measure @ "Every Other Qubit":
----------------------------------------------------------------------------------
0: ──Rot(0.39,0.43,0.03)─╭●──Rot(0.38,0.37,0.74)─╭●─╭●───────────────────┤  <Z>
1: ──Rot(0.86,0.87,0.73)─╰X──Rot(0.82,0.97,0.04)─╰X─╰Rot(0.51,0.08,0.46)─┤     
----------------------------------------------------------------------------------




<span style="font-family: 'Computer Modern'; font-weight: bold; font-size: 12pt;">Drawing #2: _Original Pooling Layer w/ "Second Qubit in Pair" Measure (Not Used Currently)_</span>

In [12]:
# Circuit 2: Second Qubit of each Pair
@qml.qnode(dev)
#------------------------------------------------------------------------------
def circuit2(weights):
    two_qubit_pooling(weights)
    return [qml.expval(qml.PauliZ(wire)) for wire in range(1, n_qubits, 2)]
#------------------------------------------------------------------------------

print(f'Pooling Layer Results (2 Qubits) #2:')
print(circuit2(weights))

# Draw Circuit Layer:
unit_drawer2 = qml.draw(circuit2)
print(f' -> Pooling Layer with PauliZ Measure @ "Every Other Qubit":')
print(f'-------------------------------------------------------------------------------')
print(unit_drawer2(weights))
print(f'-------------------------------------------------------------------------------\n\n')

Pooling Layer Results (2 Qubits) #2:
[tensor(0.41836457, requires_grad=True)]
 -> Pooling Layer with PauliZ Measure @ "Every Other Qubit":
-------------------------------------------------------------------------------
0: ──Rot(0.39,0.43,0.03)─╭●──Rot(0.38,0.37,0.74)─╭●─╭●───────────────────┤     
1: ──Rot(0.86,0.87,0.73)─╰X──Rot(0.82,0.97,0.04)─╰X─╰Rot(0.51,0.08,0.46)─┤  <Z>
-------------------------------------------------------------------------------




<span style="font-family: 'Computer Modern'; font-weight: bold; font-size: 12pt;">Drawing #3: _New Convolutional Layer (Updated Original Convolutional Layer)_</span>

In [47]:
# Convolutional Layer function for testing and drawing:

def quantum_conv_layer_test(weights):
    """
    Applies a quantum convolutional layer.
    """
    n_qubits = weights.shape[1]  # Number of qubits is second dimension of weights
    
    for i in range(0, n_qubits, 2):
        # First rotation on second qubit of pair:
        qml.RZ(-np.pi/2, wires=i + 1)
        
        # First set of rotations on first qubit of pair:
        qml.RZ(weights[0][i][0], wires=i)
        qml.RY(weights[0][i][1], wires=i + 1)
        
        # First CNOT gate:
        qml.CNOT(wires=[i, i + 1])
        
        # Second set of rotations on second qubit of pair:
        qml.RY(weights[0][i][2], wires=i + 1)
        
        # Second CNOT gate:
        qml.CNOT(wires=[i + 1, i])
        
        # Second rotation on first qubit of pair:
        qml.RZ(np.pi/2, wires=i)
        
# Example usage of the function within QNode:
#---------------------------------------------------------------------
n_qubits = 2
dev = qml.device('default.qubit', wires=n_qubits)

# Convolutional  Layer Test Drawing:
#---------------------------------------------------------------------
drawer_beta = qml.draw(quantum_conv_layer_test)
#---------------------------------------------------------------------

weights_b = np.random.random((3, n_qubits, 3))  # Example weights

print(f"Shape of Example Parameter: {weights_b.shape}")
print("------------------------")
print(r'Convolutional Layer Circuit (qml.draw):')
print(drawer_beta(weights_b))

Shape of Example Parameter: (3, 2, 3)
------------------------
Convolutional Layer Circuit (qml.draw):
1: ──RZ(-1.57)──RY(0.27)─╭X──RY(0.18)─╭●───────────┤  
0: ──RZ(0.89)────────────╰●───────────╰X──RZ(1.57)─┤  


<span style="font-family: 'Computer Modern'; font-weight: bold; font-size: 12pt;">Drawing #4: _New Pooling Layer (From GitHub Demo)_</span>

In [48]:
# Pooling Layer function for testing and drawing:

def pennylane_pool_layer_test(weights):
    """
    Applies two-qubit pooling operation to inputted qubits, including controlled rotation based on 
    measurement.
    """
    n_qubits = weights.shape[1]  # Determine number of qubits from weights shape:

    # Generate Gell-Mann matrices for 2-D space (single qubit operators):
    pool_operators = generate_gell_mann(2)  # NEW FUNC
    
    # Loop over active qubits in pairs # FOR PAIRS OF QUBITS
    for i in range(0, n_qubits, 2):  # FOR PAIRS OF QUBITS
        q1 = i        # First qubit:
        q2 = i + 1    # Second qubit:

        # Extract weights for current qubit pair:
        new_weights = weights[:, i, :]  # Shape (a, 3):

        # Get convolutional operators V1 and V2 from pool operators and weights:
        v1 = get_conv_op(pool_operators, new_weights[0])  # Use first set of weights for V1  # NEW FUNC
        v2 = get_conv_op(pool_operators, new_weights[1])  # Use second set of weights for V2  # NEW FUNC

        # Apply Hadamard gate to first qubit:
        qml.Hadamard(wires=q1)
        
        # Apply first controlled unitary operation:
        qml.ControlledQubitUnitary(v1, control_wires=[q1], wires=[q2])
        
        # Apply Hadamard gate to second qubit:
        qml.Hadamard(wires=q2)
        
        # Apply second controlled unitary operation:
        qml.ControlledQubitUnitary(v2, control_wires=[q2], wires=[q1])

# Example usage of the function within QNode:
#-------------------------------------------------------------------------
n_qubits = 2
dev = qml.device('default.qubit', wires=n_qubits)

@qml.qnode(dev)
def pool_test_circuit(weights):
    pennylane_pool_layer_test(weights)
    return qml.expval(qml.PauliZ(0))
#-------------------------------------------------------------------------

weights_a = np.random.random((2, n_qubits, 3))  # Example weights

# Pooling Layer Test Drawing:
#-------------------------------------------------------------------------
dev = qml.device("default.qubit", wires=n_qubits)
n_qubits = 2  # Number of qubits for pooling layer circuit drawing
drawer_alpha = qml.draw(pool_test_circuit)
#-------------------------------------------------------------------------

print(f"Shape of Example Parameter: {weights_a.shape}")
print("------------------------")
print(r'Pooling Layer Circuit (qml.draw):')
print(drawer_alpha(weights_a))

Shape of Example Parameter: (2, 2, 3)
------------------------
Pooling Layer Circuit (qml.draw):
0: ──H─╭●────────╭U(M1)─┤  <Z>
1: ────╰U(M0)──H─╰●─────┤     

M0 = 
[[ 0.41972586-0.34600348j -0.36117318-0.75740724j]
 [ 0.36117318-0.75740724j  0.41972586+0.34600348j]]
M1 = 
[[ 0.34020092-0.61841904j -0.25994962-0.65897452j]
 [ 0.25994962-0.65897452j  0.34020092+0.61841904j]]
